ARG INDEXER_VERSION=latest
ARG SF_VERSION=latest

FROM ubuntu:24.04 AS appbuilder

RUN apt-get update && \
    apt-get -y install -y \
    ca-certificates wget && \
    rm -rf /var/cache/apt /var/lib/apt/lists/*

FROM ghcr.io/streamingfast/near-firehose-indexer:$INDEXER_VERSION AS chain
FROM ghcr.io/streamingfast/firehose-near:$SF_VERSION

COPY --from=chain /app/near-firehose-indexer /app/near-firehose-indexer

COPY tools/docker/motd_node_manager /etc/motd
COPY tools/docker/scripts/. /usr/local/bin/
